// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlbumToggleController from "./album_toggle_controller"
import DropdownController from "./dropdown_controller"
import FlashController from "./flash_controller"
import FormController from "./form_controller"
import ModalController from "./modal_controller"

application.register("album-toggle", AlbumToggleController)
application.register("dropdown", DropdownController)
application.register("flash", FlashController)
application.register("form", FormController)
application.register("modal", ModalController)
